
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lorena
 */
public class principal extends javax.swing.JFrame {
    
    int nIncremento=2;
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();

        
        
    }
    public void pegarPortapapeles(String pegado){
        StringSelection ss = new StringSelection(pegado);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);  
    }
    public String copiarPortapapeles() throws UnsupportedFlavorException, IOException {
        Transferable t = Toolkit.getDefaultToolkit().getSystemClipboard().getContents(null);
        String copiado = (String) t.getTransferData(DataFlavor.stringFlavor);
        return copiado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CW Player");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel1.setText("TEXTO:");

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setText("Codificar");
        jButton1.setToolTipText("Descifra el texto o el portapapeles y lo pega en el portapapeles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel2.setText("MORSE:");

        jButton2.setMnemonic('B');
        jButton2.setText("❌");
        jButton2.setToolTipText("Borra solo el texto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setMnemonic('C');
        jButton3.setText("📋");
        jButton3.setToolTipText("Copia el texto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 255, 204));
        jButton4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton4.setText("Descodificar");
        jButton4.setToolTipText("Descifra el texto o el portapapeles y lo pega en el portapapeles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton5.setText("REPRODUCIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("CWPlayer - https://github.com/ourenseko/CWPlayer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        



        if (jTextArea1.getText().isEmpty()){
            try {
                jTextArea1.setText(copiarPortapapeles());
            } catch (UnsupportedFlavorException | IOException e) {
                JOptionPane.showMessageDialog(null, "Ingresa un texto o copialo en el portapapeles.");
            }
        }
        String texto = jTextArea1.getText().toLowerCase();
    
        
        
        
        
        texto = texto.replace(" ", "/ ");

        texto = texto.replace("a", ".- ");  
    texto = texto.replace("b", "-... ");  
    texto = texto.replace("c", "-.-. ");  
    texto = texto.replace("d", "-.. ");  
    texto = texto.replace("e", ". ");  
    texto = texto.replace("f", "..-. ");  
    texto = texto.replace("g", "--. ");  
    texto = texto.replace("h", ".... ");  
    texto = texto.replace("i", ".. ");  
    texto = texto.replace("j", ".--- ");  
    texto = texto.replace("k", "-.- ");  
    texto = texto.replace("l", ".-.. ");  
    texto = texto.replace("m", "-- ");  
    texto = texto.replace("n", "-. ");  
    texto = texto.replace("ñ", "--.-- ");  
    texto = texto.replace("o", "--- ");  
    texto = texto.replace("p", ".--. ");  
    texto = texto.replace("q", "--.- ");  
    texto = texto.replace("r", ".-. ");  
    texto = texto.replace("s", "... ");  
    texto = texto.replace("t", "- ");  
    texto = texto.replace("u", "..- ");  
    texto = texto.replace("v", "...- ");  
    texto = texto.replace("w", ".-- ");  
    texto = texto.replace("x", "-..- ");  
    texto = texto.replace("y", "-.-- ");  
    texto = texto.replace("z", "--.. ");  

    texto = texto.replace("0", "----- ");  
    texto = texto.replace("1", ".---- ");  
    texto = texto.replace("2", "..--- ");  
    texto = texto.replace("3", "...-- ");  
    texto = texto.replace("4", "....- ");  
    texto = texto.replace("5", "..... ");  
    texto = texto.replace("6", "-.... ");  
    texto = texto.replace("7", "--... ");  
    texto = texto.replace("8", "---.. ");  
    texto = texto.replace("9", "----. ");  


        jTextArea2.setText(texto);
        pegarPortapapeles(texto);


        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pegarPortapapeles(jTextArea2.getText());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        
            jTextArea1.setText(null);
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:


 Map<String, String> morseAtexto = new HashMap<>();
        morseAtexto.put(".-", "a");
        morseAtexto.put("-...", "b");
        morseAtexto.put("-.-.", "c");
        morseAtexto.put("-..", "d");
        morseAtexto.put(".", "e");
        morseAtexto.put("..-.", "f");
        morseAtexto.put("--.", "g");
        morseAtexto.put("....", "h");
        morseAtexto.put("..", "i");
        morseAtexto.put(".---", "j");
        morseAtexto.put("-.-", "k");
        morseAtexto.put(".-..", "l");
        morseAtexto.put("--", "m");
        morseAtexto.put("-.", "n");
        morseAtexto.put("--.--", "ñ");
        morseAtexto.put("---", "o");
        morseAtexto.put(".--.", "p");
        morseAtexto.put("--.-", "q");
        morseAtexto.put(".-.", "r");
        morseAtexto.put("...", "s");
        morseAtexto.put("-", "t");
        morseAtexto.put("..-", "u");
        morseAtexto.put("...-", "v");
        morseAtexto.put(".--", "w");
        morseAtexto.put("-..-", "x");
        morseAtexto.put("-.--", "y");
        morseAtexto.put("--..", "z");
        morseAtexto.put("-----", "0");
        morseAtexto.put(".----", "1");
        morseAtexto.put("..---", "2");
        morseAtexto.put("...--", "3");
        morseAtexto.put("....-", "4");
        morseAtexto.put(".....", "5");
        morseAtexto.put("-....", "6");
        morseAtexto.put("--...", "7");
        morseAtexto.put("---..", "8");
        morseAtexto.put("----.", "9");

        // Ejemplo de texto Morse: palabras separadas por "   ", letras por " "
         String morse=jTextArea2.getText();
        StringBuilder texto = new StringBuilder();

        for (String palabra : morse.trim().split("   ")) {
            for (String letra : palabra.split(" ")) {
                texto.append(morseAtexto.getOrDefault(letra, "?"));
            }
            texto.append(" ");
        }
        
        jTextArea1.setText(texto.toString().trim());
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String morse = jTextArea2.getText();  // SOS como ejemplo
        MorseAudioPlayer.reproducirMorse(morse);


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
